
tasks:
  - before: |
      cd gitpod
      git clone https://github.com/emscripten-core/emsdk.git
      cd emsdk
      ./emsdk install latest
      ./emsdk activate latest
      source ./emsdk_env.sh
      cd ../..
  - name: Static Server
    command: |
      cd deploy
      python3 -m http.server 8080
      cd ../..
ports:
  - port: 8080
    onOpen: open-preview

vscode:
  extensions:
    - https://github.com/ArneCode/CppTools/raw/main/vscode-cpptools.vsix