# This is a basic workflow to help you get started with Actions

name: run on Pages

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches:
      - run
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: mymindstorm/setup-emsdk@v11
      
      - name: Configure CMake
        run: |
          tree
          emcmake cmake -B build/wasm
      - name: Compiling files
        run: emmake make -C build/wasm
      - name: pushing wasm file to Pages
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "github-actions"
          git fetch
          git status
      - name: really pushing this time
        run: |
          tree
          chmod u+x ./push_to_page.sh
          ./push_to_page.sh
      - name: git adding
        run: |
          git add wasm/
          git commit -m "${{github.event.head_commit.message}}"
          git push